### ISSUE TITLE
Nether geschrottet

### ISSUE THREAD

**Issue by MrRageGaming** [Wolvaen/VulpusLupus-Community-Server#4]
Wegen der "keine Wither-Skelette im Nether"-Problematik folgte ich dem recht zeitaufwendigen Rat, einen Skelett-Spawner in den Nether zu stellen. Das Ding führte aber zu Nichts außer einem Freiflug vom Server und nun ist der Nether wohl Schrott, weil bei jedem Beitritt des Nethers und erneutem Verbinden, wenn man bereits IM Nether war, fliegt man direkt wieder vom Server. Log angehängt. Crash passierte, nachdem der Spawner 100% hatte und "versuchte" das Skelett zu spawnen.
[minecraft nether kaputt.docx](https://github.com/Wolvaen/VulpusLupus-Community-Server/files/1755247/minecraft.nether.kaputt.docx)

EDIT: Hänge btw. im Nether fest, zurioko (vermutlich) auch (noch)

**Comment by Wolvaen** [comment]
[Solved] Einige Mods wurden geupdated und die EnderIO.replaceWitherSkelettons option in den Configs disabled.
