### ISSUE TITLE
[Bug] Chaos Guardian

### ISSUE THREAD

**Issue by MrRageGaming** [Wolvaen/VulpusLupus-Community-Server#6]
Die verstärkte Version des Ender Drachens namens "Chaos Guardian" aus dem "Draconic Evolution" Mod ist extremst buggy. Schießt schneller als eine Minigun und sprengt so binnen Sekunden die ganze Insel, ganz zu schweigen davon - da ja alle Schüsse "Homing Missiles" sind - dass man in irgendeiner Art und Weise eine Chance hätte zu überleben, geschweige denn zu töten.

In diesem Zuge daher auch die Bitte um ein weiteres Mal Wiederherstellen des Inventars aus dem Grabstein, da ja die ganze Insel gesprengt wurde und man so nicht mehr rankommt.

EDIT: Im Übrigen wurde das mit Mapfe zusammen getestet, er kann es bestätigen und es wäre nicht ratsam es selbst nochmal zu versuchen (jedenfalls nicht mit Inventar), denn das Vieh killt auch Leute, die sich im Creative-Modus befinden.

**Comment by Wolvaen** [comment]
@MrRageGaming 
![lesson-learnt-gg-and-bye-bye](https://user-images.githubusercontent.com/36759728/37059627-3bf2ac5e-218e-11e8-82a4-06d03da39f66.jpg)
